version: '3'

services:

  node_api:
    build: .
    environment:
      - PORT=3000
      - NODE_ENV="dockerized"
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    networks:
      - db
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - db
    restart: always

networks:
  db:
    driver: bridge